<?php

use yii\helpers\Url;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;

use kartik\grid\GridView;
use kartik\date\DatePicker;


$this->title = 'Orders';
$this->params['breadcrumbs'][] = $this->title;


$exportConfig = [
    GridView::PDF => [
        'label' => Yii::t('kvgrid', 'PDF'),
        'icon' => $isFa ? 'file-pdf-o' : 'floppy-disk',
        'iconOptions' => ['class' => 'text-danger'],
        'showHeader' => true,
        // 'showPageSummary' => true,
        'showFooter' => true,
        'showCaption' => true,
        'filename' => Yii::t('kvgrid', 'grid-export'),
        'alertMsg' => Yii::t('kvgrid', 'The PDF export file will be generated for download.'),
        'options' => ['title' => Yii::t('kvgrid', 'Portable Document Format')],
        'mime' => 'application/pdf',
        'config' => [
            'mode' => 'c',
            'format' => 'A4-L',
            'destination' => 'D',
            'marginTop' => 20,
            'marginBottom' => 20,
            'cssInline' => '.kv-wrap{padding:20px;}' .
                '.kv-align-center{text-align:center;}' .
                '.kv-align-left{text-align:left;}' .
                '.kv-align-right{text-align:right;}' .
                '.kv-align-top{vertical-align:top!important;}' .
                '.kv-align-bottom{vertical-align:bottom!important;}' .
                '.kv-align-middle{vertical-align:middle!important;}' .
                '.kv-page-summary{border-top:4px double #ddd;font-weight: bold;}' .
                '.kv-table-footer{border-top:4px double #ddd;font-weight: bold;}' .
                '.kv-table-caption{font-size:1.5em;padding:8px;border:1px solid #ddd;border-bottom:none;}',
            'methods' => [
                'SetHeader' => [
                    ['odd' => $pdfHeader, 'even' => $pdfHeader]
                ],
                'SetFooter' => [
                    ['odd' => $pdfFooter, 'even' => $pdfFooter]
                ],
            ],
            'options' => [
                'title' => $title,
                'subject' => Yii::t('kvgrid', 'PDF export generated by kartik-v/yii2-grid extension'),
                'keywords' => Yii::t('kvgrid', 'krajee, grid, export, yii2-grid, pdf')
            ],
            'contentBefore'=>'',
            'contentAfter'=>''
        ]
    ],
];


$columns = [
    [
        'class' => 'kartik\grid\ExpandRowColumn',
        'value' => function ($model, $key, $index, $column) {
            return GridView::ROW_COLLAPSED;
        },
        'detailUrl' => Url::to(['/order/detail']),
        'expandIcon' => '<i class="fa fa-plus-square-o"></i>',
        'collapseIcon' => '<i class="fa fa-minus-square-o"></i>',
        'visible' => true
    ],
    [
        'attribute' => 'invoice_no',
        'vAlign'=>'middle',
        'width'=>'120px',
        'visible' => in_array('invoice_no', $subData['visibleAttributes']),
    ],
    [
        'class' => 'kartik\grid\EditableColumn',
        'attribute'=>'order_status_id',
        'hAlign'=>'center',
        'vAlign'=>'middle',
        'editableOptions'=> function ($model, $key, $index, $this) {
            return [
                'header' => Yii::t('order', 'Order Status'),
                'size' => 'md',
                'inputType' => \kartik\editable\Editable::INPUT_DROPDOWN_LIST ,
                'displayValueConfig' => $this->context->subData['orderStatusesHtml'],
                'data' => ArrayHelper::map($model->store->orderStatuses, 'order_status_id', 'name'),
                'formOptions' => [
                    'action' => Url::toRoute('/order/editable'),
                ]
            ];
        },
        'filterType' => GridView::FILTER_SELECT2,
        'filterWidgetOptions'=>[
            'data' => $subData['orderStatuses'], 
            'options' => [
                // 'multiple' => true,
                'placeholder' => Yii::t('order', 'Any status')
            ],
            'pluginOptions' => [
                'allowClear' => true,
            ],
        ],
        'format' => 'raw',
        'visible' => in_array('order_status_id', $subData['visibleAttributes']),
    ],
    [
        'attribute' => 'store_id',
        'hAlign' => 'center',
        'vAlign' => 'middle',
        'width' => '120px',
        'value' => function ($model) {
            return $model->store->name;
        },
        'filterType' => GridView::FILTER_SELECT2,
        'filter'=> $subData['userStores'],
        'filterWidgetOptions' => [
            'options' => [
                // 'multiple' => true,
            ],
            'pluginOptions' => [
                // 'data' => $orderStatuses,
                'allowClear' => true
            ],
        ],
        'filterInputOptions' => [
            'placeholder' => Yii::t('order', 'Any status')
        ],
        'format' => 'raw',
        'visible' => in_array('store_id', $subData['visibleAttributes']),
    ],
    [
        'class' => 'kartik\grid\EditableColumn',
        'attribute' => 'payment_status_id',
        'hAlign' => 'center',
        'vAlign' => 'middle',
        'editableOptions' => function ($model, $key, $index, $this) {
            return [
                'header' => Yii::t('order', 'Payment Status'),
                'size' => 'md',
                'inputType' => \kartik\editable\Editable::INPUT_DROPDOWN_LIST ,
                'displayValueConfig' => $this->context->subData['paymentStatusesHtml'],
                'data' => $this->context->subData['paymentStatusesList'],
                'formOptions' => [
                    'action' => Url::toRoute('/order/editable'),
                ]
            ];
        },
        'filterType' => GridView::FILTER_SELECT2,
        'filterWidgetOptions'=>[
            'data' => $subData['paymentStatusesList'], 
            'options' => [
                // 'multiple' => true,
            ],
            'pluginOptions' => [
                'allowClear' => true
            ],
        ],
        'filterInputOptions' => [
            'placeholder' => Yii::t('order', 'Any status')
        ],
        'format' => 'raw',
        'visible' => in_array('payment_status_id', $subData['visibleAttributes']),
    ],
    [
        'attribute' => 'create_time',
        'hAlign' => 'center',
        'vAlign' => 'middle',
        'width' => '280px',
        'value' => function ($model) {
            return Yii::$app->formatter->asDatetime($model->create_time);
        },
        'filterType' => GridView::FILTER_DATE_RANGE ,
        'filterWidgetOptions' => [
            'hideInput' => true,
            'pluginOptions' => [
                'autoclose' => true,
                'timePicker' => false,
                'format' => 'DD-MM-YYYY',
                'separator' => ' to ',
                'opens'=>'left',
                'ranges' => [
                    Yii::t('kvdrp', "Today") => ["moment().startOf('day')", "moment()"],
                    Yii::t('kvdrp', "Yesterday") => ["moment().startOf('day').subtract(1,'days')", "moment().endOf('day').subtract(1,'days')"],
                    Yii::t('kvdrp', "Last {n} Days", ['n' => 7]) => ["moment().startOf('day').subtract(6, 'days')", "moment()"],
                    Yii::t('kvdrp', "Last {n} Days", ['n' => 30]) => ["moment().startOf('day').subtract(29, 'days')", "moment()"],
                    Yii::t('kvdrp', "This Month") => ["moment().startOf('month')", "moment().endOf('month')"],
                    Yii::t('kvdrp', "Last Month") => ["moment().subtract(1, 'month').startOf('month')", "moment().subtract(1, 'month').endOf('month')"],
                ],
            ],
            'containerTemplate' => '
                <span class="input-group-addon">
                    <i class="glyphicon glyphicon-calendar"></i>
                </span>
                <span class="form-control text-right" style="overflow: hidden;">
                    <span class="pull-left">
                        <span class="range-value">{value}</span>
                    </span>
                    <b class="caret"></b>
                    {input}
                </span>
            ',
            'pluginEvents' => [
                'show.daterangepicker' => 'function() { console.log("show.daterangepicker"); }',
                'hide.daterangepicker' => 'function() { console.log("hide.daterangepicker"); }',
                'apply.daterangepicker' => 'function(start, end) {'
                . 'jQuery("#w0").yiiGridView("applyFilter");'
                . '}',
                'cancel.daterangepicker' => 'function() { console.log("cancel.daterangepicker"); }',
            ],
        ],
        'visible' => in_array('create_time', $subData['visibleAttributes']),
    ],
    [
        'class' => '\kartik\grid\ActionColumn',
        'template' => '{view} {update}',
        'contentOptions' => ['nowrap'=>'nowrap']
    ],
    ['class' => '\kartik\grid\CheckboxColumn'],
];

?>
<div class="order-index">

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => $columns,
        'showPageSummary' => true,
        'export' => [
            'fontAwesome' => true
        ],
        'exportConfig' => $exportConfig,
        'panel' => [
            'heading' => '<h3 class="panel-title"><i class="fa fa-file-text-o"></i>' . Yii::t('order', 'Orders') . '</h3>',
            'type' => GridView::TYPE_PRIMARY,
        ],
        'toolbar' => [
            ['content'=>
                Html::a('<i class="fa fa-plus"></i>', ['create'], ['data-pjax' => true, 'title' => Yii::t('order', 'Create Order'), 'class'=>'btn btn-success']) . ' '.
                Html::a('<i class="fa fa-repeat"></i>', ['index'], ['data-pjax' => true, 'class' => 'btn btn-default', 'title' => Yii::t('kvgrid', 'Reset Grid')])
            ],
            '{export}',
            '{toggleData}'
        ],
        'floatHeader'=>true,
        'striped' => true,
        'condensed' => true,
        'responsive' => true,
        'hover' => true,
        'pjax' => true,
        'pjaxSettings' => [
            'neverTimeout' => true,
        ]

    ]); ?>

</div>